name: Build and Test

on:
    push:
        branches:
            - main
        tags:
            - v*
    pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Upgrade setuptools, pip and wheel
        run: python -m pip install -U setuptools pip wheel
      - name: Install hatch
        run: python -m pip install hatch
      - name: Run tests
        run: python -m hatch run tests-cov
        env:
          PYTEST_ADDOPTS: --color=yes
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
