name: Build and Test

on:
    push:
        branches:
            - main
        tags:
            - v*
    pull_request:

jobs:
  test:
    name: Run tests py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade setuptools, pip and wheel
        run: python -m pip install -U setuptools pip wheel
      - name: Install hatch
        run: python -m pip install hatch
      - name: Run tests
        run: python -m hatch run tests-cov
        env:
          PYTEST_ADDOPTS: --color=yes
      - name: Upload coverage report to Codecov
        if: ${{ matrix.python-version == '3.10' }}
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
